### ISSUE TITLE
Content covering other site parts

### ISSUE THREAD

**Issue by bitcoinuser** [nodetec/notestack#114]
Hi,

Content covering other site parts.

See: https://blogstack.io/naddr1qq98yetxv4ex2mnrv4esz9rhwden5te0wfjkccte9ejxzmt4wvhxjmczypl62m6ad932k83u6sjwwkxrqq4cve0hkrvdem5la83g34m4rtqegqcyqqq823ceqj05d

![Captura de tela de 2023-02-24 18-49-32](https://user-images.githubusercontent.com/1178856/221300006-ffa148c5-9e82-458e-aa7e-e3d1d9bc670d.png)

**Comment by ChristianChiarulli** [comment]
https://blogstack.io/naddr1qq98yetxv4ex2mnrv4esz9rhwden5te0wfjkccte9ejxzmt4wvhxjmczypl62m6ad932k83u6sjwwkxrqq4cve0hkrvdem5la83g34m4rtqegqcyqqq823ceqj05d

should be fixed, thanks for the issue!
