### ISSUE TITLE
When I open an article on mobile, automatically jump to bottom of the page

### ISSUE THREAD

**Issue by bitcoinuser** [nodetec/notestack#121]
Hi,

When I open an article on mobile, automatically jump to bottom of the page.

https://user-images.githubusercontent.com/1178856/221359794-022e0abd-4c52-45c0-9250-e8a82ec946e8.mp4

**Comment by ChristianChiarulli** [comment]
this is due to the comment section being autofocused for some reason

**Comment by MAHcodes** [comment]
temporarily fix 
https://github.com/nodetec/blogstack/commit/b5bf8507cc4585397716e643c84ecd40d4388bd6

**Comment by bitcoinuser** [comment]
> temporarily fix [b5bf850](https://github.com/nodetec/blogstack/commit/b5bf8507cc4585397716e643c84ecd40d4388bd6)

Looks like not applied, right? because I still reproduce the problem

**Comment by MAHcodes** [comment]
I guess it's scrolling before the focus on document, please let me know if it worked or not.

**Comment by ChristianChiarulli** [comment]
seems to work for me on mobile, what browser are you using @bitcoinuser

**Comment by bitcoinuser** [comment]
> seems to work for me on mobile, what browser are you using @bitcoinuser

Brave browser

**Comment by ChristianChiarulli** [comment]
I'm rewriting the site, you can find the new one at https://notestack.com
