### ISSUE TITLE
If I click on a external link to a blogstack article, never opens.

### ISSUE THREAD

**Issue by bitcoinuser** [nodetec/notestack#122]
Hi

If I click on a external link to a blogstack article, never opens.

https://user-images.githubusercontent.com/1178856/221359869-8f116900-fded-4675-85c2-fb66270367b6.mp4

**Comment by ChristianChiarulli** [comment]
could you link the article here so I can test?

**Comment by bitcoinuser** [comment]
> could you link the article here so I can test?

I think any blogstack link article posted here do not open when I try to open with mobile. Lets test this one:

https://blogstack.io/naddr1qqyrgdtpvf3rjvp3qyv8wumn8ghj7un9d3shjtnndehhyapwwdhkx6tpdspzqwlsccluhy6xxsr6l9a9uhhxf75g85g8a709tprjcn4e42h053vaqvzqqqr4guuymsj5

**Comment by bitcoinuser** [comment]
> > could you link the article here so I can test?
> 
> I think any blogstack link article posted here do not open when I try to open with mobile. Lets test this one:
> 
> https://blogstack.io/naddr1qqyrgdtpvf3rjvp3qyv8wumn8ghj7un9d3shjtnndehhyapwwdhkx6tpdspzqwlsccluhy6xxsr6l9a9uhhxf75g85g8a709tprjcn4e42h053vaqvzqqqr4guuymsj5

This opened.
