### ISSUE TITLE
I think the comment part could be improved.

### ISSUE THREAD

**Issue by bitcoinuser** [nodetec/notestack#123]
Hi,

I think the comment part could be improved. I think doesn't make sense show get key button. Newbies will not understand it. I suggest:

1- Show a button called Comment
2- When the user click on Comment button, will work the same way as clicking on Get key.
3- When the user click on Comment button, will show the field to insert the comment and a new button called Post.

**Comment by ChristianChiarulli** [comment]
I agree, maybe we can get https://github.com/fiatjaf/nocomment to expose a way to change the button text

**Comment by ChristianChiarulli** [comment]
I'm rewriting the site, you can find the new one at https://notestack.com
