### ISSUE TITLE
I posted a test comment on an article on blogstack but I don't see it on blocstack but I see on Nostr

### ISSUE THREAD

**Issue by bitcoinuser** [nodetec/notestack#124]
Hi,

I posted a test comment on an article on blogstack but I don't see it on blocstack but I see on Nostr

Article on blogstack: https://blogstack.io/naddr1qq0ky6t5vdhkjm3qd35kw6r5de5kueeqwaskcmr9w3ejqmn0wd68yqg5waehxw309aex2mrp0yhxgctdw4eju6t0qgspszndgtravnuv89vdn5gd6kjpzl424n4gulucq7q7nff3xm84dycrqsqqqa28j63y0k

Comment on nostr: https://nostrich.com/thread/note1x6w74xqd6mftz3uku428rgxuvn4p35gwdz3r9c3tc6ldc94k9zxskfx476

**Comment by ChristianChiarulli** [comment]
hmm, I'm not able to see any content for either of these links

**Comment by ChristianChiarulli** [comment]
https://habla.news/a/naddr1qq0ky6t5vdhkjm3qd35kw6r5de5kueeqwaskcmr9w3ejqmn0wd68yqg5waehxw309aex2mrp0yhxgctdw4eju6t0qgspszndgtravnuv89vdn5gd6kjpzl424n4gulucq7q7nff3xm84dycrqsqqqa28j63y0k

I don't think it works on habla.news either

**Comment by bitcoinuser** [comment]
Ok, will close.

**Comment by bitcoinuser** [comment]
Hum, I posted a comment on this article and I don't see the comment on blogstack:

https://blogstack.io/naddr1qqyrgdtpvf3rjvp3qyv8wumn8ghj7un9d3shjtnndehhyapwwdhkx6tpdspzqwlsccluhy6xxsr6l9a9uhhxf75g85g8a709tprjcn4e42h053vaqvzqqqr4guuymsj5

**Comment by bitcoinuser** [comment]
You can see my comment on this note: note1lkq5xl4xu9t3wj62patr8uw6y6m9gxa2qrvedhrfkaexlazfft9q5z3fxx

**Comment by ChristianChiarulli** [comment]
I'm rewriting the site, you can find the new one at https://notestack.com
