### ISSUE TITLE
Empty page when navigating to naddr

### ISSUE THREAD

**Issue by djseeds** [nodetec/notestack#134]
Hi all, great job with blogstack!

While working on a nip-23 publishing I noticed I'm not able to refresh the page / navigate directly to a post's URL. Instead of showing the post, the page is completely blank.

Not super familiar with react, but I assume this is a routing issue of some sort, or that the event isn't being read on load.

Repro steps:
1. Navigate to a post
2. Refresh the page
3. The page is blank

Example post:
https://blogstack.io/naddr1qqyxyvtyvf3k2v3cqy28wumn8ghj7un9d3shjtnyv9kh2uewd9hsygr4hu34xxhflxxx9x2m5pcereygat28t96nw8tr6l0ag677r0agj5psgqqqw4rs98y2fg

**Comment by hashratez** [comment]
Same issue, no direct access to blog posts.  See screenshot: https://www.mediafire.com/view/vpcmq46v4rem8qn/bug.png/file

Here is the post URL which will come up blank: https://blogstack.io/naddr1qqyrwdnpvdsnzdrzqy28wumn8ghj7un9d3shjtnyv9kh2uewd9hsyg9xl9mfzvwu9tnt0ak4p77gez38q6dtydqwyatws564lxalrtdmgypsgqqqw4rs8d9ayc

**Comment by ChristianChiarulli** [comment]
this should be fixed, thanks for reporting
