### ISSUE TITLE
Change to next layout instead of tabs

### ISSUE THREAD

**Issue by Lcarv20** [nodetec/notestack#138]
I believe it would be nicer to work with the layouts and paths like /settings/relays or /settings/[npub] and render accordingly instead of using tabs. I can work on this soon.
[Next Layouts](https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts)

**Comment by ChristianChiarulli** [comment]
I'm rewriting the site, you can find the new one at https://notestack.com
