### ISSUE TITLE
Following / Followers are wiped out ?

### ISSUE THREAD

**Issue by peter-power-594** [nodetec/notestack#143]
Ladies & Gentlemen,

I don't know if it is the right behavior or a bug, when I started to follow some profiles on blogstack, all the profiles I was following on Primal were gone 😲 Not cool at all. (Disclaimer : I'm a beginner with Nostr)

Cheers and keep the good work 💪

**Comment by ChristianChiarulli** [comment]
I'm rewriting the site, you can find the new one at https://notestack.com
